name: Java Build and Docker

on:
  push:
    branches:
      - main

jobs:
  build multi stage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Build Docker image
      run: docker build -t multistage -f docker/Dockerfile .
      
    - name: Run Docker container
      run: docker run multistage

