name: Java Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK and Build Docker Image
        run: |
          # Use the Dockerfile mentioned earlier
          docker build -t benchmark-image-21-distroless -f docker/Dockerfile .
        working-directory: ${{ github.workspace }}


      - name: Run Docker Container
        run: |
          # Run Docker container
          docker run java-docker-jre-example

