name: Java Build and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile Java code
      run: javac HelloWorld.java

  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t benchmark-image-21-distroless -f docker/Dockerfile .
      
    - name: Run Docker container
      run: docker run benchmark-image-21-distroless

